# Need rover to be installed and the other services to be running

# Compose all the subgraphs together into a supergraph
build-supergraph-schema:
	rover supergraph compose --config ./supergraph-config.yaml > supergraph.graphql
