federation_version: 2
subgraphs:
  app-store:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4001
  storytelling:
    routing_url: http://localhost:4002
    schema:
      subgraph_url: http://localhost:4002
  datasets:
    routing_url: http://localhost:4003
    schema:
      subgraph_url: http://localhost:4003
